### ISSUE TITLE
Addon not working anymore

### ISSUE THREAD

**Issue by renaiku** [HENDRIX-ZT2/jpog-blender#3]
Hello,

The addon is not showing the import/export options in the menu anymore.

Coud you update the addon ?

Thanks.

**Comment by zachguo** [comment]
<img width="495" alt="Screen Shot 2021-12-19 at 9 53 23 PM" src="https://user-images.githubusercontent.com/3478203/146718458-95fcbfe3-4ad5-4d1d-8ddc-483668166b56.png">
<img width="516" alt="Screen Shot 2021-12-19 at 9 53 43 PM" src="https://user-images.githubusercontent.com/3478203/146718502-059094d9-b9e1-4ab8-9351-20a71d6aced5.png">
Yup, no `TMD`.

Blender 3.0.0

**Comment by HENDRIX-ZT2** [comment]
Needs to be updated to 2.8+ API. PRs welcome!

**Comment by Ceratothesocrates** [comment]
Hello there. i am pretty new to these matters. Should i install an older version of blender or is there any other way i could use this add on?

**Comment by HENDRIX-ZT2** [comment]
This addon only works with Blender 2.79.

**Comment by HENDRIX-ZT2** [comment]
Thanks to @AdventureT there is now support for newer blender versions in the master branch!
